version: "3.9"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.5.6
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config_heimdall:/config
  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:2.6.0
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=tpco.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DNSPLUGIN=duckdns
      - DUCKDNSTOKEN=89f727a1-e2a8-43a2-b804-20b82d48071e
    depends_on:
      - heimdall
      - sonarr
      - radarr
      - lidarr
      - jackett
      - bazarr
    volumes:
      - ./config_swag:/config
    ports:
      - "80:80"
      - "443:443"
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/downloads:/downloads
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - ./radarr/config:/config
      - ./radarr/downloads:/downloads
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    volumes:
      - ./lidarr/config:/config
      - ./lidarr/downloads:/downloads
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    volumes:
      - ./bazarr/config:/config
      - ./bazarr/downloads:/downloads
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./jellyfin/media:/media
    restart: unless-stopped